name: Create Branch on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Create Branch
        run: |
          git branch issue-${{ github.event.issue.number }}-${{ github.event.issue.title | slugify }}
          git checkout issue-${{ github.event.issue.number }}-${{ github.event.issue.title | slugify }}
          git push --set-upstream origin issue-${{ github.event.issue.number }}-${{ github.event.issue.title | slugify }}
